### ISSUE TITLE
Cinder V2 api causes volume

### ISSUE THREAD

**Issue by yosifkit** [emccode/rexray#168]
@clintonskitson, Here is the debug log you requested from your custom build.  It is related to https://github.com/rackspace/gophercloud/issues/449 and https://github.com/hashicorp/terraform/issues/2817.
```console
$ ./rexray volume create --volumename=yosifkit --size=5 -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] volume driver initialized                     provider=docker
INFO[0000] os driver initialized                         provider=linux
INFO[0000] storage driver initialized                    provider=Openstack
PANI[0000] Expected HTTP response code [200 201] when accessing [POST http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes], but got 202 instead
{"volume": {"status": "creating", "user_id": "7ee3b4617e494f50a826e5e532e7c1a4", "attachments": [], "links": [{"href": "http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "self"}, {"href": "http://192.168.14.26:8776/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-10-28T14:38:40.793759", "description": null, "volume_type": null, "name": "yosifkit", "replication_status": "disabled", "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {}, "id": "41d7056b-7104-4d8d-8163-785da85648b3", "size": 5}} 
panic: Expected HTTP response code [200 201] when accessing [POST http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes], but got 202 instead
{"volume": {"status": "creating", "user_id": "7ee3b4617e494f50a826e5e532e7c1a4", "attachments": [], "links": [{"href": "http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "self"}, {"href": "http://192.168.14.26:8776/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-10-28T14:38:40.793759", "description": null, "volume_type": null, "name": "yosifkit", "replication_status": "disabled", "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {}, "id": "41d7056b-7104-4d8d-8163-785da85648b3", "size": 5}} [recovered]
	panic: Expected HTTP response code [200 201] when accessing [POST http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes], but got 202 instead
{"volume": {"status": "creating", "user_id": "7ee3b4617e494f50a826e5e532e7c1a4", "attachments": [], "links": [{"href": "http://192.168.14.26:8776/v2/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "self"}, {"href": "http://192.168.14.26:8776/ace18eb5d9e84d0db72344b13cb2ecd5/volumes/41d7056b-7104-4d8d-8163-785da85648b3", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-10-28T14:38:40.793759", "description": null, "volume_type": null, "name": "yosifkit", "replication_status": "disabled", "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {}, "id": "41d7056b-7104-4d8d-8163-785da85648b3", "size": 5}} [recovered]
	panic: (*logrus.Entry) (0xa69ba0,0xc82016b540)

goroutine 1 [running]:
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc820048140, 0xc82018b020, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820183000, ...)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:105 +0x618
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc8201f34c0, 0xc8201f35a8, 0x1, 0x1)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:150 +0x99
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc820048140, 0xc8201f35a8, 0x1, 0x1)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc8201f35a8, 0x1, 0x1)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:102 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/emccode/rexray/drivers/storage/openstack.(*driver).CreateVolume(0xc820011db0, 0xc820176900, 0x7ffcb2b43e97, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:606 +0xaa6
github.com/emccode/rexray/core.(*sdm).CreateVolume(0xc8201f5170, 0xc8201b4000, 0x7ffcb2b43e97, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/core/drivers_storage.go:359 +0x181
github.com/emccode/rexray/rexray/cli.(*CLI).initVolumeCmds.func4(0xc82016e000, 0xc82016a700, 0x0, 0x4)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cmds_volume.go:85 +0x189
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc82016e000, 0xc82016a6c0, 0x4, 0x4, 0x0, 0x0)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:534 +0x869
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200d2540, 0x0, 0x0)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc82012a900)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc82012a900)
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
	/Users/clintonkitson/go/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fcb3fc21b18, 0x72, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201c00d0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201c00d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201c0070, 0xc8201d4000, 0x1000, 0x1000, 0x0, 0x7fcb3fc1b050, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201b4010, 0xc8201d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fcb3fbdb000, 0xc8201b4010, 0xc8201d2058, 0xc8201d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201b00e0, 0xc8201d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201c42a0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201c42a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201d2000)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:685 +0xc78

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc8201d2000)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:686 +0xc9d

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7fcb3fc21bd8, 0x72, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82015de20, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82015de20, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82015ddc0, 0xc8201dc000, 0x1000, 0x1000, 0x0, 0x7fcb3fc1b050, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820024200, 0xc8201dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fcb3fbdb000, 0xc820024200, 0xc8200a5d38, 0xc8201dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820173ee0, 0xc8201dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82017c720)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82017c720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200a5ce0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:685 +0xc78

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc8200a5ce0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:686 +0xc9d

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7fcb3fc21a58, 0x72, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201f68b0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201f68b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201f6850, 0xc8201eb000, 0x1000, 0x1000, 0x0, 0x7fcb3fc1b050, 0xc820012170)
	/usr/local/Cellar/go/1.5/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201b40b8, 0xc8201eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fcb3fbdb000, 0xc8201b40b8, 0xc8201d2478, 0xc8201eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201b1c40, 0xc8201eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201c54a0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201c54a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201d2420)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:685 +0xc78

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc8201d2420)
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:686 +0xc9d
```

**Comment by clintonskitson** [comment]
Thanks for the info, I will update this with a resolution for Openstack environments.

**Comment by clintonskitson** [comment]
An "error creating volume" error was being returned when creating a volume.  This was caused since the `gophercloud` API bindings for Openstack are only capable of speaking the v1 API of Cinder.  The API bindings look for `volume` by default and leverage the URL returned by that service.  If Openstack is configured to return the v2 API in that place, then this error will be encountered.  Fix the URL for `volume` to something similar to `http://<cinder ip>:8776/v1/%(tenant_id)s`.  A `volumev2` can still be configured to point to the new Cinder v2 API.
