### ISSUE TITLE
CentOS 7 Runtime Error

### ISSUE THREAD

**Issue by stephentknight** [emccode/rexray#245]
This error is appearing when trying to start the rexray daemon on CentOS7:

CentOS version details:
```
[root@dc01-worker-02 ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@dc01-worker-02 ~]# rpm -qa | grep kernel
kernel-tools-3.10.0-327.3.1.el7.x86_64
kernel-tools-libs-3.10.0-327.3.1.el7.x86_64
kernel-3.10.0-327.3.1.el7.x86_64
kernel-3.10.0-229.el7.x86_64
```
Error after running 'rexray start':
```
PANI[0000] runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: (*logrus.Entry) (0x1565880,0xc82043e880)
[signal 0xb code=0x1 addr=0x10 pc=0x89b5b9]

goroutine 1 [running]:
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82005e100, 0xc82044f1a0, 0x0, 0x19e00000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc82043e840, ...)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc8200b4f10, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0xdf
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc82005e100, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).retryCheckResp(0xc820279930, 0xc8202799b8, 0xc8200fc7e0, 0x171eca0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:132 +0x159
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).Authenticate(0xc820279930, 0xc82028e840, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:57 +0x25d
github.com/emccode/rexray/drivers/storage/scaleio.(*driver).Init(0xc82026cc30, 0xc8200878b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/scaleio/scaleio.go:79 +0x6ed
github.com/emccode/rexray/core.(*RexRay).InitDrivers(0xc8200878b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/core/rexray.go:85 +0x16fb
github.com/emccode/rexray/rexray/cli.(*CLI).preRun(0xc820272000, 0xc820277a40, 0x20874f0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:288 +0x2ca
github.com/emccode/rexray/rexray/cli.(*CLI).(github.com/emccode/rexray/rexray/cli.preRun)-fm(0xc820277a40, 0x20874f0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:142 +0x48
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc820277a40, 0x20874f0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:517 +0x911
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200ac700, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc820272000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc820272000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```
The package was installed using the shell script, defaulting to the latest version.

My configuration file has the following: (etc/rexray/config.yml)
```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
scaleio:
  endpoint: https://xxx/api
  insecure: true
  userName: admin
  password: xxx
  systemName: clus1
  protectionDomainName: protection_domain1
  storagePoolName: capacity_pool1
```
Could you let me know if this is a known issue and how I could resolve it?

**Comment by clintonskitson** [comment]
Can you run it interactively first, rexray volume -l debug? And post
results?

It looks to be an authentication problem.

**Comment by stephentknight** [comment]
This is what I get:

```
[root@dc01-worker-02 ~]# rexray volume -l debug
INFO[0000] Start init()
INFO[0000] Start configRegistration()
INFO[0000] Start newDriver()
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] scaleio
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
PANI[0000] runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: (*logrus.Entry) (0x1565880,0xc820438440)
[signal 0xb code=0x1 addr=0x10 pc=0x89b5b9]

goroutine 1 [running]:
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82005e140, 0xc82048dc20, 0x0, 0x19e00000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820438400, ...)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc8200b4f10, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0xdf
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc82005e140, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).retryCheckResp(0xc8202a6750, 0xc8202a67d8, 0xc820156540, 0x171eca0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:132 +0x159
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).Authenticate(0xc8202a6750, 0xc820295410, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:57 +0x25d
github.com/emccode/rexray/drivers/storage/scaleio.(*driver).Init(0xc82027d530, 0xc82010f130, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/scaleio/scaleio.go:79 +0x6ed
github.com/emccode/rexray/core.(*RexRay).InitDrivers(0xc82010f130, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/core/rexray.go:85 +0x16fb
github.com/emccode/rexray/rexray/cli.(*CLI).preRun(0xc820286000, 0xc82020ba40, 0xc820275ae0, 0x0, 0x2)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:288 +0x2ca
github.com/emccode/rexray/rexray/cli.(*CLI).(github.com/emccode/rexray/rexray/cli.preRun)-fm(0xc82020ba40, 0xc820275ae0, 0x0, 0x2)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:142 +0x48
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc82020ba40, 0xc820275980, 0x2, 0x2, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:517 +0x911
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc82020a380, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc820286000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc820286000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 3 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by stephentknight** [comment]
Tried the same credentials (URl + username + password) with ScaleIO-Py and it seems to authenticate fine.
```
>>> from scaleiopy.scaleio import ScaleIO
>>> sio = ScaleIO("https://192.168.111.221/api","admin","xxx",False, "ERROR")
>>> print (sio.sds)
[<ScaleIO_SDS> @ 11755024:
                drl_mode: Volatile
            fault_set_id: None
                      id: 045f2c0b00000002...
```

**Comment by clintonskitson** [comment]
Can you paste your config.yml file in here?  What version of Java is
running the gateway?

**Comment by clintonskitson** [comment]
Sorry just noticed you did have the config earlier.  The Java version and
gateway version would help.

**Comment by stephentknight** [comment]
Config.yml
```
[root@dc01-worker-01 ~]# cat /etc/rexray/config.yml
rexray:
  logLevel: warn
  osDrivers:
  - linux
  storageDrivers:
  - scaleio
  volumeDrivers:
  - docker
scaleio:
  endpoint: https://192.168.111.221/api/login
  insecure: false
  userName: admin
  password: xxx
  systemName: clus1
  protectionDomainName: protection_domain1
  storagePoolName: capacity_pool1
```
Java version:
```
[root@dc01-scaleio-01 ~]# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
ScaleIO RPM version:
```
EMC-ScaleIO-gateway-1.32-3455.5.noarch
```

Thanks

**Comment by clintonskitson** [comment]
Can you try running Java 1.6?  I ran into an issue the other day similar to
this and it related to the SSL portion of Java being used by SIO being too
weak for what Go natively supports in 1.5.

From what I can

**Comment by stephentknight** [comment]
Running it with openjdk 1.6, I still get an error:

```
[root@dc01-worker-01 ~]# rexray device -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] [scaleio]
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
INFO[0000] os driver initialized                         provider=linux
PANI[0000] runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: (*logrus.Entry) (0x18fa760,0xc82043c5c0)
[signal 0xb code=0x1 addr=0x10 pc=0x8a5cc9]

goroutine 1 [running]:
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82005e140, 0xc82044e2d0, 0x0, 0x19e00000000, 0x0, 0x              0, 0x0, 0x0, 0x0, 0xc82043c580, ...)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc8200b4f10, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0xdf
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc82005e140, 0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc8200b4ff8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).retryCheckResp(0xc82027fba0, 0xc82027fc28, 0xc8200fc7              e0, 0x1b211a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:132 +0x159
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).Authenticate(0xc82027fba0, 0xc82027d830, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:57 +0x25d
github.com/emccode/rexray/drivers/storage/scaleio.(*driver).Init(0xc82025d9b0, 0xc820085810, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/scaleio/scaleio.go:79 +0x6ed
github.com/emccode/rexray/core.(*RexRay).InitDrivers(0xc820085810, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/core/rexray.go:85 +0x16fd
github.com/emccode/rexray/rexray/cli.(*CLI).preRun(0xc820274000, 0xc8200ad500, 0xc820270d80, 0x0, 0x2)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:288 +0x2ca
github.com/emccode/rexray/rexray/cli.(*CLI).(github.com/emccode/rexray/rexray/cli.preRun)-fm(0xc8200ad500, 0xc820270d80, 0x0,               0x2)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:142 +0x48
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc8200ad500, 0xc820270c20, 0x2, 0x2, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:517 +0x911
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200ac700, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc820274000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc820274000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```
Java version:
```
java version "1.6.0_37"
OpenJDK Runtime Environment (IcedTea6 1.13.9) (rhel-1.13.9.4.el7_1-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

**Comment by clintonskitson** [comment]
How about the password?  Can you ensure it is in single quotes and that
there are no extra spaces after variables on each line?

**Comment by stephentknight** [comment]
The config.yml looks like this:
```
[root@dc01-worker-01 ~]# cat /etc/rexray/config.yml
rexray:
  logLevel: warn
  osDrivers:
  - linux
  storageDrivers:
  - scaleio
  volumeDrivers:
  - docker
scaleio:
  endpoint: https://192.168.111.221/api
  insecure: false
  userName: admin
  password: 'xxx'
  systemName: clus1
  protectionDomainName: protection_domain1
  storagePoolName: capacity_poolSSD
```
Does this look correct?

**Comment by clintonskitson** [comment]
Can you take a look at the SIO gateway logs?  There should be an access log
showing that the request made it to the service and then a Catalina log
that shows the errors.

**Comment by stephentknight** [comment]
The logs are empty if I run rexray. If I run ScaleIO-py and login and fetch SDS info, log entries appear in the gateway logs. 

The binary for rexray appears to be bombing out before a connection is established. Iptables is disabled on all hosts, SELinux disabled, latest CentOS7 with all updates. I don't think I am missing anything.

**Comment by clintonskitson** [comment]
Hmm.. One last try on the config?  Can you copy paste what we have in the
example section of the docs for scaleio?  Then just copy paste your vars in
there?

I did see something like that which was related to the Java rev.  I will
check into that version change that I made.

**Comment by stephentknight** [comment]
Do you mean this? http://rexray.readthedocs.org/en/master/user-guide/storage-providers/scaleio/

I have used it as the basis for rexray config, otherwise I am scratching my head trying to figure this one out.

**Comment by clintonskitson** [comment]
Here's a few things to verify.

1) set the `insecure: true`
2) Here is my java rev that I am using `java-1.6.0-openjdk-1.6.0.37-1.13.9.4.el6_7.x86_64`
3) Ensure that the the java in path is the correct one and that it is not executing an arbitrary java version.
4) Ensure you can `telnet 192.168.111.221 443` from the host running RR

If these don't work I can post a snippet of Go to troubleshoot further for you.

**Comment by stephentknight** [comment]
Setting insecure to true seems to have helped, it's not crashing anymore. Thank you!
However, the storage driver is failing to initialize:
```
INFO[0000] volume driver initialized                     provider=docker
Oops, an error occured!

  no storage drivers initialized
```
The volume driver is working fine as you can see from the above.

**Comment by clintonskitson** [comment]
Can you run with "-l debug"?

**Comment by stephentknight** [comment]
With debug:
```
[root@dc01-worker-01 ~]# rexray device get -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] [scaleio]
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
INFO[0000] volume driver initialized                     provider=docker
INFO[0000] os driver initialized                         provider=linux
DEBU[0000] error initializing driver                     driverName=ScaleIO error.provider=ScaleIO error.endpoint="https://192.168.111.221/api" error.insecure=true error.useCerts=false
Oops, an error occured!

  no storage drivers initialized
```

**Comment by clintonskitson** [comment]
Ok, I am assuming it is actually erroring out when trying to discover the local instance ID now.  Is the OS you are trying to run this from a configured SDC yet?

```
	if sdcGUID, err = goscaleio.GetSdcLocalGUID(); err != nil {
		return goof.WithFieldsE(fields, "error getting sdc local guid", err)
	}

	if d.sdc, err = d.system.FindSdc(
		"SdcGuid",
		strings.ToUpper(sdcGUID)); err != nil {
		fields["sdcGuid"] = sdcGUID
		return goof.WithFieldsE(fields, "error finding sdc", err)
	}
```

**Comment by clintonskitson** [comment]
@stephentknight closing this per our conversation.  The resolution here was

1) Running java 1.6 for the gateway
2) Ensuring the SDC where RR was running was properly registered as an SDC

We will be addressing the squashing of errors further in 0.4
