### ISSUE TITLE
Error starting rexray service

### ISSUE THREAD

**Issue by akamalov** [emccode/rexray#271]
Environment: RHEL 7.2
Rexray: 0.3.1
Storage driver: scaleio

Having problem starting rexray:

```
[root@node1 rexray]# systemctl -l status rexray
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2016-01-28 12:44:13 EST; 4min 5s ago
  Process: 22724 ExecStart=/usr/bin/rexray start -f (code=exited, status=0/SUCCESS)
 Main PID: 22724 (code=exited, status=0/SUCCESS)

Jan 28 12:44:13 node1.localnet.net rexray[22724]: 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
Jan 28 12:44:13 node1.localnet.net rexray[22724]: MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"
Jan 28 12:44:13 node1.localnet.net rexray[22724]: Binary: /usr/bin/rexray
Jan 28 12:44:13 node1.localnet.net rexray[22724]: SemVer: 0.3.1
Jan 28 12:44:13 node1.localnet.net rexray[22724]: OsArch: Linux-x86_64
Jan 28 12:44:13 node1.localnet.net rexray[22724]: Branch: v0.3.1
Jan 28 12:44:13 node1.localnet.net rexray[22724]: Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Jan 28 12:44:13 node1.localnet.net rexray[22724]: Formed: Wed, 30 Dec 2015 16:12:44 EST
Jan 28 12:44:13 node1.localnet.net rexray[22724]: time="2016-01-28T12:44:13-05:00" level=error msg="default module(s) failed to start"
Jan 28 12:44:13 node1.localnet.net rexray[22724]: time="2016-01-28T12:44:13-05:00" level=error msg="service initialized failed"
[root@node1 rexray]# 
```

My /etc/rexray/rexray.yml file is:

```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
    volume:
      mount:
        preempt: true
      unmount:
        ignoreusedcount: true
scaleio:
    endpoint:             https://XXXXXXXXX
    insecure:             false
    useCerts:             true
    userName:             admin
    password:             XXXXXXXXXX
    systemID:             0
    systemName:           cluster1
    protectionDomainID:   0
    protectionDomainName: domain1
    storagePoolID:        0
    storagePoolName:      pool1

```

Am I missing something ? do I need to have /etc/rexray/config.yml file ? I apologize, by documentation is not clear (at least to me) on steps what it takes to bring up rexray environment + scaleio. Also, in my other issue I opened, there is a dead URL link for activating volume drivers, so I do not even know how to activate it at this point...

Thanks,

Alex

**Comment by clintonskitson** [comment]
Alex,

The documentation was incorrect. It should be `/etc/rexray/config.yml`.  Before starting REX-Ray as a service you should work with `rexray env` to verify your options were configured properly or `rexray volume` to test functionality.

Btw. The `ignoreusedcount` should only be used if you are using mesos-module-dvdi.

```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
    volume:
      mount:
        preempt: true
      unmount:
        ignoreusedcount: true
scaleio:
    endpoint:             https://XXXXXXXXX
    insecure:             false
    userName:             admin
    password:             XXXXXXXXXX
    systemName:           cluster1
    protectionDomainName: domain1
    storagePoolName:      pool1
```

**Comment by akamalov** [comment]
Thanks so much for the response. As of this moment, rexray  daemon fails immediately upon start. Yep, I am planing on using mesos-module-dvdi, once rexray gets configured. Here is my configuration info:

File: <b> /etc/rexray/rexray.env</b>
```
DOCKER_VOLUMETYPE=
LINUX_VOLUME_ROOTPATH=/data
SCALEIO_USERNAME=admin
SCALEIO_USECERTS=true
SCALEIO_STORAGEPOOLNAME=pool1
DOCKER_SIZE=0
SCALEIO_PASSWORD=XXXXXXXXX
REXRAY_STORAGEDRIVERS=scaleio
SCALEIO_SYSTEMNAME=cluster1
SCALEIO_ENDPOINT=https://XXXXXXXX
REXRAY_VOLUMEDRIVERS=docker
REXRAY_HOST=tcp:/127.0.0.1/:7979
REXRAY_LOGLEVEL=warn
SCALEIO_SYSTEMID=0
DOCKER_AVAILABILITYZONE=
SCALEIO_USERID=admin
SCALEIO_INSECURE=false
SCALEIO_PROTECTIONDOMAINNAME=domain1
REXRAY_VOLUME_MOUNT_PREEMPT=true
SCALEIO_STORAGEPOOLID=0
REXRAY_VOLUME_UNMOUNT_IGNOREUSEDCOUNT=true
DOCKER_IOPS=0
SCALEIO_PROTECTIONDOMAINID=0
```
File: <b> /etc/rexray/config.yml </b>

```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
    volume:
      mount:
        preempt: true
      unmount:
        ignoreusedcount: true
scaleio:
    endpoint:             https://XXXXXXXX
    insecure:             false
    useCerts:             true
    userName:             admin
    password:             XXXXXX
    systemID:             0
    systemName:           cluster1
    protectionDomainID:   0
    protectionDomainName: domain1
    storagePoolID:        0
    storagePoolName:      pool1
```

Running command <b>rexray volume</b> is resulting in panic:

```
[root@node1 rexray]# rexray volume
PANI[0000] runtime error: invalid memory address or nil pointer dereference 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: (*logrus.Entry) (0x18fa760,0xc8203ae8c0)
[signal 0xb code=0x1 addr=0x10 pc=0x8a5cc9]

goroutine 1 [running]:
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc820014180, 0xc8204523c0, 0x0, 0x19e00000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8203ae780, ...)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc820220f00, 0xc820220fe8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0xdf
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc820014180, 0xc820220fe8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc820220fe8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).retryCheckResp(0xc82029c0d0, 0xc82029c158, 0xc8204c6a80, 0x1b211a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:132 +0x159
github.com/emccode/rexray/vendor/github.com/emccode/goscaleio.(*Client).Authenticate(0xc82029c0d0, 0xc8202c9d40, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio/api.go:57 +0x25d
github.com/emccode/rexray/drivers/storage/scaleio.(*driver).Init(0xc820267e30, 0xc8200877c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/scaleio/scaleio.go:79 +0x6ed
github.com/emccode/rexray/core.(*RexRay).InitDrivers(0xc8200877c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/core/rexray.go:85 +0x16fd
github.com/emccode/rexray/rexray/cli.(*CLI).preRun(0xc820280000, 0xc8200a7dc0, 0x27f44b8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:288 +0x2ca
github.com/emccode/rexray/rexray/cli.(*CLI).(github.com/emccode/rexray/rexray/cli.preRun)-fm(0xc8200a7dc0, 0x27f44b8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:142 +0x48
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc8200a7dc0, 0x27f44b8, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:517 +0x911
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200a6700, 0x0, 0x0)
        /home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc820280000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc820280000)
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
        /home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
[root@node1 rexray]# 
```

BTW, I installed based on the doc in GitHub:

```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
```

**Comment by clintonskitson** [comment]
Thanks for the detailed response.  I believe you got your example from http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/scaleio/

I put a slimmed down version above that you should be able to leverage. 1) the parameter names like `system` with `ID` and `name` are the same thing, but the ID would take priority.  I excluded the ID fields from the config I posted.  2) Are you referring to the `/api` in your URL?  This is the true endpoint.

Reading through the docs again, it isn't clear in this driver what the initial example is.  That should reference the fact that it has all configurable items for ScaleIO.  The example at the bottom is a "working" example.  Updating it to include a proper `/api` endpoint would also make sense.  Sorry for the confusion.

**Comment by clintonskitson** [comment]
One last thing, we do have an open PR https://github.com/emccode/rexray/pull/266/files

This updates some of the SIO documentation for troubleshooting and the API example. I will take some of what was discussed here and expand further in that PR to ensure the docs are clear.

**Comment by akamalov** [comment]
Thanks again, for your response.  Earlier, in one of your posts, you've mentioned:

```...The documentation was incorrect. It should be /etc/rexray/config.yml ```, but in the URL https://github.com/emccode/rexray/pull/266/files, in line ```39```, you're referencing to config file as ```rexray.yml``` and not ```config.yml.``` Here is my updated config file:

File: <b>/etc/rexray/config.yml </b>

```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
    volume:
      mount:
        preempt: true
      unmount:
        ignoreusedcount: true
scaleio:
    endpoint:             https://10.9.XXX.XXX
    insecure:             false
    useCerts:             true
    userName:             admin
    password:             XXXXXXX
    systemName:           cluster1
    protectionDomainName: domain1
    storagePoolName:      pool1
```

File: <b>/etc/rexray/rexray.env</b>

```
DOCKER_VOLUMETYPE=
LINUX_VOLUME_ROOTPATH=/data
SCALEIO_USERNAME=admin
SCALEIO_USECERTS=true
SCALEIO_STORAGEPOOLNAME=pool1
DOCKER_SIZE=0
SCALEIO_PASSWORD=XXXXXXXX
REXRAY_STORAGEDRIVERS=scaleio
SCALEIO_SYSTEMNAME=cluster1
SCALEIO_ENDPOINT=https://10.9.XXX.XXX
REXRAY_VOLUMEDRIVERS=docker
REXRAY_HOST=tcp:/127.0.0.1/:7979
REXRAY_LOGLEVEL=warn
DOCKER_AVAILABILITYZONE=
SCALEIO_USERID=admin
SCALEIO_INSECURE=false
SCALEIO_PROTECTIONDOMAINNAME=domain1
REXRAY_VOLUME_MOUNT_PREEMPT=true
REXRAY_VOLUME_UNMOUNT_IGNOREUSEDCOUNT=true
DOCKER_IOPS=0
```

Still, daemon is failing to start:

```
[root@node1 rexray]# systemctl start rexray
[root@node1 rexray]# systemctl -l status rexray
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2016-01-28 16:16:54 EST; 1s ago
  Process: 26268 ExecStart=/usr/bin/rexray start -f (code=exited, status=0/SUCCESS)
 Main PID: 26268 (code=exited, status=0/SUCCESS)

Jan 28 16:16:53 node1.localnet.net rexray[26268]: 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
Jan 28 16:16:53 node1.localnet.net rexray[26268]: MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Binary: /usr/bin/rexray
Jan 28 16:16:53 node1.localnet.net rexray[26268]: SemVer: 0.3.1
Jan 28 16:16:53 node1.localnet.net rexray[26268]: OsArch: Linux-x86_64
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Branch: v0.3.1
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Formed: Wed, 30 Dec 2015 16:12:44 EST
Jan 28 16:16:54 node1.localnet.net rexray[26268]: time="2016-01-28T16:16:54-05:00" level=error msg="default module(s) failed to start"
Jan 28 16:16:54 node1.localnet.net rexray[26268]: time="2016-01-28T16:16:54-05:00" level=error msg="service initialized failed"
[root@node1 rexray]# 
```
Journal log files:

```
[root@node1 rexray]# journalctl -l -r -u rexray
-- Logs begin at Thu 2016-01-28 14:49:20 EST, end at Thu 2016-01-28 16:18:42 EST. --
Jan 28 16:16:54 node1.localnet.net rexray[26268]: time="2016-01-28T16:16:54-05:00" level=error msg="service initialized failed"
Jan 28 16:16:54 node1.localnet.net rexray[26268]: time="2016-01-28T16:16:54-05:00" level=error msg="default module(s) failed to start
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Formed: Wed, 30 Dec 2015 16:12:44 EST
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Branch: v0.3.1
Jan 28 16:16:53 node1.localnet.net rexray[26268]: OsArch: Linux-x86_64
Jan 28 16:16:53 node1.localnet.net rexray[26268]: SemVer: 0.3.1
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Binary: /usr/bin/rexray
Jan 28 16:16:53 node1.localnet.net rexray[26268]: MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"
Jan 28 16:16:53 node1.localnet.net rexray[26268]: 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
Jan 28 16:16:53 node1.localnet.net rexray[26268]: $$$$$$c    $$""""        Y$$$Pcccc $$$$$$c   c$$$cc$$$c   c$$"
Jan 28 16:16:53 node1.localnet.net rexray[26268]: [[[,/[[['  [[cccc       '[[,,[['   [[[,/[[['  ,[[ '[[,  '[[,[[['
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ;;;;'';;;; ;;;;''''    ';;;,  .,;; ;;;;'';;;;   ;;';;  ';;.   ;;;;'
Jan 28 16:16:53 node1.localnet.net rexray[26268]: :::::::..  .,::::::    .,::      .::::::::..    :::.  .-:.     ::-.
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ⁿⁿ             ⁿ ⁿ^
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ╙Ω▀█ ▓██ⁿ    └█▀██▀▓█├█Å
Jan 28 16:16:53 node1.localnet.net rexray[26268]: û▌├▓█▓▓▓██ⁿ ¡▓▓▓▓▓▓▓▓█▓╪
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ⁿ  .▄▄▓▓▓▓▄▄┌ ╖__▓_▄▄▄▄▄*Oⁿ
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Ω_.└██▓▀ⁿÇⁿ▀▀▀▀▀▀█≡▀▀▀▀▀   µ
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ⌠  ├▓▓▓▓▓ⁿ▄▓▓▓▓▓▓▓┐▄▓▓▓▓  └
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ├▓▓▓▌█═┴▓▄╒▀▄_▄▌═¢▓▓▓  ╚
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ~ ├▓▓  ▄  _     ╒  ┌▄▓▓  Γ
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ⌐ ├_                τ▀▓  Σ⌐└
Jan 28 16:16:53 node1.localnet.net rexray[26268]: µ ├▓▀▀L   └ⁿ  ▀   ▀ ▓▓█w ▓▓▓▀ìⁿ
Jan 28 16:16:53 node1.localnet.net rexray[26268]: µ ├▓▓▓▓█▀█▓▓_▓▓███▓▓▓▓▓  ▓▓▓▓▓Ω4
Jan 28 16:16:53 node1.localnet.net rexray[26268]: _ ├▓▓▓▓▓▓▓▓▓~▓▓▓▓▓▓▓▓▓▓  ▄4▄▓▓▓██
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ├▓▓▓▓▓▓▓▄▄═▄▓▓▓▓▓▓▓▓▓  π ⌐▄▓▓█║n
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ╞  ├▓▓▓▓▓▄▄__^^▓▓▓▌▓▓▓▓▓  ▓   /▓▓▓
Jan 28 16:16:53 node1.localnet.net rexray[26268]: │  ├▓▓▓▓▓▌≡,__▄▓▓▓█▓▓▓▓▓ ╞█~   Y,┐
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Γ  ├▓▓▓▓▓█▀ⁿ█▌▓Ω]█▓▓▓▓▓▓ ├▓
Jan 28 16:16:53 node1.localnet.net rexray[26268]: 'ⁿ_  ,▄▄▄▄▄▄▄▄▄█_▄▄▄▄▄▄▄▄▄ⁿ▀~██
Jan 28 16:16:53 node1.localnet.net rexray[26268]: F▌▓▌█ⁿⁿⁿ  ⁿ└▀ⁿ██▓▀▀▀▀▀▀▀▀▀▀▌▓▓▓▌
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ,▄▓▓▓▓▓▓^██▓▓▓▓▓▓▓▓▓▓▓▓▄▀▄▄▓▓Ω▄
Jan 28 16:16:53 node1.localnet.net rexray[26268]: _J┤▓▓▓▓▓▓▓▓▓▓▓▓▓├█▓█▓▀Γ
Jan 28 16:16:53 node1.localnet.net rexray[26268]: │▄▓▓ _▓▓▓▓▓▓▓▓▓┌▓▓▓▓▓█
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ,_▄▀▓▓ ▓▓ ▓▓▓▓▓▓▓▓▓▓▓█
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ╒▓▓▌▓▓▓▓▓▓▓▓▓▓▀▓▄▄.
Jan 28 16:16:53 node1.localnet.net rexray[26268]: Σ▄▓▓▓▓▓▓▓▓▓▓▄π
Jan 28 16:16:53 node1.localnet.net rexray[26268]: ⌐▄Q▓▄Ç▓▄,▄_
Jan 28 16:16:53 node1.localnet.net systemd[1]: Starting rexray...
lines 1-41

```

**Comment by clintonskitson** [comment]
Check your endpoint of `https://10.9.XXX.XXX`.  This should be `https://10.9.XXX.XXX/api`.  

You also have to other flags set.  The `insecure` flag would meant that you have loaded the necessary certs locally and commands like wget and curl to the endpoint URL don't result in SSL problems.  The `useCerts` flag is for leveraging those built into REX-Ray, so wouldn't be ideal here.

I would start with `rexray volume -l debug` before trying to start as a service.  If this command works, then starting the service will work.

**Comment by akamalov** [comment]
It worked! Thanks so much!! Here is the working setup:

File: <b>/etc/rexray/rexray.env</b>
```
DOCKER_VOLUMETYPE=
LINUX_VOLUME_ROOTPATH=/data
SCALEIO_USERNAME=admin
SCALEIO_USECERTS=false
SCALEIO_STORAGEPOOLNAME=pool1
DOCKER_SIZE=0
SCALEIO_PASSWORD=XXXXXXX
REXRAY_STORAGEDRIVERS=scaleio
SCALEIO_SYSTEMNAME=cluster1
SCALEIO_ENDPOINT=https://10.9.XXX.XXX/api
REXRAY_VOLUMEDRIVERS=docker
REXRAY_HOST=tcp:/127.0.0.1/:7979
REXRAY_LOGLEVEL=warn
DOCKER_AVAILABILITYZONE=
SCALEIO_USERID=admin
SCALEIO_INSECURE=true
SCALEIO_PROTECTIONDOMAINNAME=domain1
REXRAY_VOLUME_MOUNT_PREEMPT=true
REXRAY_VOLUME_UNMOUNT_IGNOREUSEDCOUNT=true
DOCKER_IOPS=0
```

File: <b>/etc/rexray/config.yml</b>
```
rexray:
    logLevel: warn
    osDrivers:
    - linux
    storageDrivers:
    - scaleio
    volumeDrivers:
    - docker
    volume:
      mount:
        preempt: true
      unmount:
        ignoreusedcount: true
scaleio:
    endpoint:             https://10.9.XXX.XXX/api
    insecure:             true
    useCerts:             false
    userName:             admin
    password:             XXXXXXX
    systemName:           cluster1
    protectionDomainName: domain1
    storagePoolName:      pool1
```
Once these two portions correctly configured, command ```rexray volume -l debug``` worked right away and I was able to bring up the daemon

Thanks so much yet again for your help!!!

**Comment by clintonskitson** [comment]
Glad to hear you got that sorted out.  I will be updating docs to address
what we highlighted here so thank you for being patient.  Just to be clear
it is the config.yml file that is being used to start rexray.

**Comment by akamalov** [comment]
Thanks again

**Comment by clintonskitson** [comment]
FYI @akamalov I have updated the documentation per this conversation in PR https://github.com/emccode/rexray/pull/267.  In this PR there is also an update to the driver for lerveraging multiple storage pools through the storage type setting.  These changes and exactly what is described in the PR docs will work with `0.3.2-rc2` that comes out next week.
